//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Affiliate_Marketing_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionCodeTracking
    {
        public int trackingId { get; set; }
        public string promotionCode { get; set; }
        public System.DateTime timeOfUsing { get; set; }
        public double totalAmoutOfOrder { get; set; }
        public double moneyEarned { get; set; }
    }
}
