//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Affiliate_Marketing_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionCode
    {
        public string promotionCode1 { get; set; }
        public Nullable<double> percentEarn { get; set; }
        public Nullable<bool> isWorking { get; set; }
    }
}
